name: Sync to Borealis Dataverse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Send repo to Dataverse 
        uses: IQSS/dataverse-uploader@v1.7
        with:
          DATAVERSE_TOKEN: ${{ secrets.MY_API_KEY_EXPIRE_2027_09_03 }}
          DATAVERSE_SERVER: 'https://borealisdata.ca'
          DATAVERSE_DATASET_DOI: 'doi:10.5683/SP4/RYRFZU'
          PUBLISH: 'false'
